### PR TITLE
(#532) Double horizontal lines are displayed when there is no pager at 1024px and lower

### LINKED ISSUE #532: Double horizontal lines are displayed when there is no pager at 1024px and lower
Double horizontal lines appear below the Start Over | Modify Search Criteria link and above the delighters at the bottom of the page at 1024px and lower on react-app-dev.

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  Go to https://react-app-dev.cancer.gov/clinical-trials-search-app/develop/r?loc=0&rl=1&t=C80078
2.  Switch the screen to 1024 px or lower
3. Double horizontal lines are displayed when there is no pager at 1024px and lower

### What's the expected result?
- There should be no horizontal lines when there is no pager present like desktop. See screenshot.
- Padding can be removed from top above "Select all on page" but should stay at bottom between "Select all on page" and the large icons (Have a question, here to help).

Clinical-Trials-Search-Results---National-Cancer-Institute

### What's the actual result?
- Double horizontal lines are displayed when there is no pager at 1024px and lower.

@mworrest , @sarinapadilla , please provide the AC/ Expected Result.

### Additional details / screenshot 

image
image

### Related Tickets
* Issue #9999
* Issue #9999

### PR DESCRIPTION
**Pull request by alerosad**
- edited ResultsPage.scss to only display one horizontal bar, when screen is 1024px or lower

Closes #532

### CODE REVIEW

**Comment by alerosad** [comment]
https://react-app-dev.cancer.gov/clinical-trials-search-app/pr-536

**Comment by alinai** [comment]
@alerosad , The horizontal line is disappearing between the pager and "Select all on page" when there is a pager at 1024 and below. I think it should appear the way it is on Prod. 

image
image

**Comment by alinai** [comment]
@alerosad , can you please check if the following AC is in place for this ticket?
image


@alerosad , when pager appears, can we make the spacing between horizontal lines consistent with Prod? Please see the screen-shot which shows how the spacing is in Prod.

image

**Comment by alinai** [comment]
@alerosad , Also, at mobile breakpoint, at the top of the page and at the bottom of the page, the spacing between the two horizontal lines in the pager and the spacing between the "Select all on page" is not consistent with Prod. 

image

image

**Comment by mworrest** [comment]
Please remove spacing per the second bullet AC.

**Comment by alinai** [comment]
> Please remove spacing per the second bullet AC.

@alerosad , please see the comment of @mworrest. Thanks!

**Comment by alinai** [comment]
@alerosad , The length of the search criteria box is longer than Prod, ODE and develop at all breakpoints.

image
image

**Comment by alinai** [comment]
Verified: 
1. Double horizontal lines does not appear below the Start Over | Modify Search Criteria link and above the delighters at the bottom of the page at 1024px and lower on react-app-dev.https://react-app-dev.cancer.gov/clinical-trials-search-app/pr-536/r?loc=0&rl=1&t=C3908 and https://react-app-dev.cancer.gov/clinical-trials-search-app/pr-536/r?loc=0&rl=1 
2. At mobile breakpoint, at the top of the page and at the bottom of the page, the spacing between the two horizontal lines in the pager and the spacing between the "Select all on page" is close to Prod on react-app-dev.https://react-app-dev.cancer.gov/clinical-trials-search-app/pr-536/r?loc=0&rl=1&t=C3908
3. The spacing between "Start Over" link and "Select all on page" is reasonable when there is no pager at smaller breakpoint  react-app-dev.https://react-app-dev.cancer.gov/clinical-trials-search-app/pr-536/r?loc=0&rl=1&t=C3908 
4. Verified that the search criteria box has the same length as Prod on  react-app-dev.https://react-app-dev.cancer.gov/clinical-trials-search-app/pr-536/r?loc=0&rl=1&t=C3908

**Comment by sarinapadilla** [comment]
@alerosad @alinai @arcepaul I tested all of the scenarios and this PR looks good to me!

**Comment by alinai** [comment]
> @alerosad @alinai @arcepaul I tested all of the scenarios and this PR looks good to me!

Thanks for confirming @sarinapadilla

File: src/views/ResultsPage/ResultsPage.jsx [hunk 1]
```diff
@@ -474,7 +474,11 @@ const ResultsPage = () => {
 										Print Selected
 									</button>
 								</div>
-								<div className="results-page__pager">
+								<div
+									className={
+										'results-page__' +
+										(pagerExists ? 'pager' : 'no_pages_pager')
```
Comment (arcepaul) [inline src/views/ResultsPage/ResultsPage.jsx:480]: see comment below.  these shouldnt be separate elements.  rather, it should be a modifier

File: src/views/ResultsPage/ResultsPage.scss [hunk 2]
```diff
@@ -30,20 +30,33 @@
...
+	&__no_pages_pager{
+		padding: 5px 0;
+		width: 100%;
+
+		@media screen and (min-width: 1025px) {
+      border: 0;
+      width: auto;
+		}
+
+	}
```
Comment (arcepaul) [inline src/views/ResultsPage/ResultsPage.scss:60]: modify this to be a modifier of pager element like so:
```
&__pager {
  padding: 12px 0 12px;
  width: 100%;

  @media screen and (min-width: 1025px) {
    border: 0;
    width: auto;
  }
  
  &--no-pages {
    padding: 5px 0;
	 width: 100%;
  }
}
```
You will have to modify the ternary for the class declaration on the results page

File: src/views/ResultsPage/ResultsPage.jsx [hunk 3]
```diff
@@ -600,6 +603,7 @@ const ResultsPage = () => {
 			</div>
 		);
 	};
+	const pagerExists = trialResults != null && trialResults.total / 10 > 1;
```
Comment (seyilonge-nci) [inline src/views/ResultsPage/ResultsPage.jsx:606]: How is the denominator value derived (10)?

Comment (alerosad) [reply src/views/ResultsPage/ResultsPage.jsx:606]: Since we do 10 results per page, that's how I derived it

Comment (alerosad) [reply src/views/ResultsPage/ResultsPage.jsx:606]: so I used the value to determine how many pages the pager has listed

**Comment by alerosad** [comment]
made the change Seyi requested, resultsPerPage is no longer hardcoded as 10, but now has a variable passed in for the 10 value

**Review by seyilonge-nci — APPROVED** [review]

File: src/views/ResultsPage/ResultsPage.jsx [hunk 4]
```diff
@@ -474,7 +475,10 @@ const ResultsPage = () => {
 										Print Selected
 									</button>
 								</div>
-								<div className="results-page__pager">
+								<div
+									className={
```
Comment (arcepaul) [inline src/views/ResultsPage/ResultsPage.jsx:479]: use a string template here

File: src/views/ResultsPage/ResultsPage.jsx [hunk 5]
```diff
@@ -474,7 +475,10 @@ const ResultsPage = () => {
 										Print Selected
 									</button>
 								</div>
-								<div className="results-page__pager">
+								<div
+									className={`results-page__${
+										pagerExists ? `pager` : `no_pages`
```
Comment (arcepaul) [inline src/views/ResultsPage/ResultsPage.jsx:480]: Did you try this?  The no_pages is now a modifier, so it would be `results-page__pager--no-pages` and no longer `results-page__pager--no-pages`

Comment (alerosad) [reply src/views/ResultsPage/ResultsPage.jsx:480]: what?

Comment (alerosad) [reply src/views/ResultsPage/ResultsPage.jsx:480]: what change do you need me to make?

Comment (alerosad) [reply src/views/ResultsPage/ResultsPage.jsx:480]: wait nevermind I think I understand what you meant

File: src/views/ResultsPage/ResultsPage.jsx [hunk 6]
```diff
@@ -437,6 +438,10 @@ const ResultsPage = () => {
 			</Delighter>
 		</div>
 	);
+	const pagerExists =
+		trialResults != null && trialResults.total / resultsPerPage > 1;
+
+	console.log(pagerExists);
```
Comment (arcepaul) [inline src/views/ResultsPage/ResultsPage.jsx:444]: remove

**Comment by sarinapadilla** [comment]
This PR looks good to me on react-app-dev! Tested both no pager and pager results pages.

**Review by arcepaul — APPROVED** [review]
