### PR TITLE
(#552) Duplicate Delighters on Invalid Param Page - Mobile Breakpoint

### LINKED ISSUE #552: Delighters are appearing twice on Invalid param page at mobile breakpoint
### Issue description

Delighters are appearing twice on Invalid param page at mobile breakpoint.

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  Go to https://ncigovcdode450.prod.acquia-sites.com/about-cancer/treatment/clinical-trials/search/r?a=121&loc=0&rl=1
2. Switch to mobile breakpoint
3. Keep scrolling down and see that "Have a question" and "Which trials are good for you" appears twice.

### What's the expected result?
- "Have a question" and "Which trials are good for you" delighters should appear once at all breakpoint.

### What's the actual result?
- "Have a question" and "Which trials are good for you" appears twice at mobile breakpoint

### Related Tickets
* Issue #9999
* Issue #9999

### PR DESCRIPTION
**Pull request by seyilonge-nci**
Closes #552

* Updated DOM to move "aside" element with class `results-page__aside --side` into conditionally rendered parent container

### CODE REVIEW

**Comment by seyilonge-nci** [comment]
@alinai Please review https://react-app-dev.cancer.gov/clinical-trials-search-app/pr-553/r?a=121&loc=0&rl=1

File: src/views/ResultsPage/ResultsPage.jsx [hunk 1]
```diff
@@ -623,65 +623,64 @@ const ResultsPage = () => {
...
+								onModifySearchClick={handleRefineSearch}
+								onStartOverClick={handleStartOver}
+								searchCriteriaObject={searchCriteriaObject}
+								isLoading={isLoading}
+								trialResults={trialResults}
+							/>
+						</>
+					)}
+					<div className="results-page__content">
+						{checkIfInvalidPage() ? <> </> : <>{renderControls()}</>}
```
Comment (arcepaul) [inline src/views/ResultsPage/ResultsPage.jsx:651]: Looks like we can clean this up a little bit and simplify the render logic

Comment (seyilonge-nci) [reply src/views/ResultsPage/ResultsPage.jsx:651]: Yup. Can move the container `<article className="results-page">` up and have the conditional rendering occur inside of the container for one.

**Review by arcepaul — APPROVED** [review]
