### PR TITLE
(#562) Add friendly text for trials with trial type OTHER

### LINKED ISSUE #562: Trials with Trial Type "Other" should display "Not provided by clinicaltrials.gov"
### Issue description
The trial description page displays "Other" as the trial type for trials that return primary_purpose: "OTHER". This needs to be updated to say "Not provided by clinicaltrials.gov"

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  Go to https://ncigovcdode450.prod.acquia-sites.com/about-cancer/treatment/clinical-trials/search/v?id=NCI-2018-02261&loc=0&rl=1&t=C2989
2. Open the Trial Phase & Type accordion section

### What's the expected result?
- Trial Type is "Not provided by clinicaltrials.gov"

### What's the actual result?
- Trial Type is "Other"

### Additional details / screenshot
- Screenshot

### Related Tickets
* Issue #9999
* Issue #9999

### PR DESCRIPTION
**Pull request by adriancofie**
(#562) Add friendly text for trials with trial type OTHER

   * Replaces the trial type text of 'Other' with 'Not provided by clinicaltrials.gov'
        * Adds styling for proper casing
   * Adds cypress test case
        * Fixes typos

  Closes #562

### CODE REVIEW

**Comment by sarinapadilla** [comment]
@adriancofie After talking with Lindsay, the text shouldn't have clinicaltrials.gov be camel cased. Please update it to be "Not provided by clinicaltrials.gov"! I've updated the ticket with this requirement as well.

File: src/views/TrialDescriptionPage/TrialDescriptionPage.jsx [hunk 1]
```diff
@@ -430,6 +430,29 @@ const TrialDescriptionPage = () => {
 		return <ErrorPage initErrorsList={localState.errors} />;
 	};
 
+	const formatPrimaryPurpose = () => {
+		let formatted_purpose = false;
```
Comment (seyilonge-nci) [inline src/views/TrialDescriptionPage/TrialDescriptionPage.jsx:434]: For data type integrity, since the rest of the function sets this as a string, why not follow the same pattern here?

**Comment by alinai** [comment]
Looks good on react-app-dev.
Verified: https://react-app-dev.cancer.gov/clinical-trials-search-app/pr-563/v?id=NCI-2018-02261&loc=0&rl=1&t=C2989

@sarinapadilla , @KateMashkinaNIH , We need to verify it on ODE and Print page.

File: src/views/TrialDescriptionPage/TrialDescriptionPage.jsx (hunk 1 above)
Comment (adriancofie) [reply src/views/TrialDescriptionPage/TrialDescriptionPage.jsx]: Good point. Initially I was going to merge the guard in the jsx with this function but I walked it back since we're so close to launch / it's a bigger change. Updated to an empty string for now!

**Review by arcepaul — APPROVED** [review]
