### PR TITLE
(#203) No Trials Search Page Live Help Link

### LINKED ISSUE #203: CTS No Trials Match Search page Live Help going to wrong queue
CTS No Trials Match Search Page is going to the regular Cancer Information LiveHelp queue instead of the CTS LiveHelp queue.

Issue Reported by CIS on 1/16:
When filling out the search form, if your selection does not turn up any clinical trials, you receive this message (found on https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/r?loc=1&rl=2&st=C66719&t=C4872&z=26554&zp=20):

No clinical trials matched your search.
For assistance, please contact the Cancer Information Service. You can chat online or call 1-800-4-CANCER (1-800-422-6237).
Try a new search

Actual result:
The “chat online” is clickable and goes directly into our LiveHelp queue. However, we realized that the queue it directs to is incorrect—it takes you to the Cancer Information queue and not the Clinical Trials queue as it should. 

Expected result: 
The "chat online" is clickable and goes directly into the Clinical Trials queue within LiveHelp. The link should pass the parameter icf_22 = 2174, so the link is https://livehelp.cancer.gov/app/chat/chat_landing?_icf_22=2174

### PR DESCRIPTION
**Pull request by seyilonge-nci**
Closes #203

* Using form action to open "chat online" live help
* Updated style and swapped "p" for "div" element

### CODE REVIEW

File: src/views/ResultsPage/ResultsPage.jsx [hunk 1]
```diff
@@ -366,10 +366,10 @@ const ResultsPage = ({ location, tracking }) => {
         <ul>
           <li>Zip Code</li>
         </ul>
-        <p>
+        <div>
```
Comment (arcepaul) [inline src/views/ResultsPage/ResultsPage.jsx:369]: why are you switching this to a div?

Comment (seyilonge-nci) [reply src/views/ResultsPage/ResultsPage.jsx:369]: Console warning for `form` tag being a descendant of the `p` tag

Comment (arcepaul) [reply src/views/ResultsPage/ResultsPage.jsx:369]: ah, because of the other change...gotcha

**Review by karlikpj — APPROVED** [review]

**Review by arcepaul — APPROVED** [review]
